# Generated by Django 5.1.6 on 2025-06-02 03:12

import activos.modelos.Parte
import activos.modelos.mantenimientos
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_area', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=25, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('disponibilidad', models.CharField(choices=[('ON', 'EN OPERACIÓN'), ('BK', 'EN RESERVA/MANTENIMIENTO'), ('OFF', 'FUERA DE OPERACIÓN PERMANENTE')], max_length=3)),
                ('fecha_instalacion', models.DateField()),
                ('fecha_updated', models.DateField(auto_now=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images_maquinas/')),
                ('link', models.FileField(blank=True, null=True, upload_to='archivos_maquinas/')),
            ],
        ),
        migrations.CreateModel(
            name='mantenimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRE', 'PREVENTIVO'), ('CORR', 'CORRECTIVO'), ('DIC', 'PREDICTIVO')], max_length=5)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_planificada', models.DateField()),
                ('fecha_ejecutada', models.DateField(blank=True, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to=activos.modelos.mantenimientos.mantenimientos.nombrar)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parte', models.IntegerField()),
                ('codigo_parte', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=130)),
                ('descripcion', models.TextField()),
                ('mantenimiento', models.TextField(blank=True, null=True)),
                ('anexo1', models.FileField(blank=True, null=True, upload_to='images_partes/')),
                ('anexo2', models.FileField(blank=True, null=True, upload_to='archivos_partes/')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images_repuestos/')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='archivos_repuestos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_subArea', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=200)),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.area')),
            ],
        ),
        migrations.AddField(
            model_name='maquina',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.subarea'),
        ),
        migrations.CreateModel(
            name='SubParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('num_subparte', models.IntegerField()),
                ('nombre', models.CharField(max_length=130)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.parte')),
                ('repuesto', models.ManyToManyField(related_name='subpartes', to='activos.repuesto')),
            ],
        ),
    ]
