# Generated by Django 5.1.6 on 2025-06-02 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_repuesto_bodega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parte',
            old_name='anexo2',
            new_name='anexo',
        ),
        migrations.RenameField(
            model_name='parte',
            old_name='anexo1',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='ParteRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.parte')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.repuesto')),
            ],
        ),
        migrations.DeleteModel(
            name='SubParte',
        ),
    ]
