# Generated by Django 5.1.6 on 2025-06-03 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_rename_anexo2_parte_anexo_rename_anexo1_parte_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuesto',
            old_name='bodega',
            new_name='cantidad_bodega',
        ),
    ]
