# Generated by Django 5.1.6 on 2025-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_rename_bodega_repuesto_cantidad_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='num_maquina',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
