# Generated by Django 5.1.6 on 2025-04-06 23:31

import activos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0018_alter_parte_anexo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=130)),
                ('marca', models.CharField(max_length=130)),
                ('modelo', models.CharField(max_length=130)),
                ('descripción', models.TextField()),
                ('repuesto', models.BooleanField(default=False)),
                ('anexo1', models.ImageField(blank=True, null=True, upload_to=activos.models.SubParte.inner)),
                ('anexo2', models.FileField(blank=True, null=True, upload_to=activos.models.SubParte.inner)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.parte')),
            ],
        ),
    ]
