# Generated by Django 5.1.6 on 2025-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0019_subparte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='codigo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
