# Generated by Django 5.1.6 on 2025-04-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0020_alter_maquina_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='num_parte',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
