# Generated by Django 5.1.6 on 2025-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0021_parte_num_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='subparte',
            name='num_subparte',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
