# Generated by Django 5.1.6 on 2025-04-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0022_subparte_num_subparte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='cod_area',
            field=models.CharField(max_length=15),
        ),
    ]
