# Generated by Django 5.1.6 on 2025-04-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0023_alter_area_cod_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='maquina',
            old_name='fecha_instalación',
            new_name='fecha_instalacion',
        ),
        migrations.RenameField(
            model_name='parte',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='subparte',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
